### ISSUE TITLE
Integrate Neon Local into Docker Compose => HAProxyManager manage_branches crash

### ISSUE THREAD

**Issue by zubair-akbar** [neondatabase-labs/neon_local#10]
We're working on integrating neon local as a drop in Postgres proxy for our E2E Playwright suite The goal is to have each docker compose up spin up a new, isolated branch of our database and automatically tear it down when we stop.

With this configuration: 

```
  neon-db:
    image: neondatabase/neon_local:latest
    ports:
      - '5432:5432'
    environment:
      - NEON_API_KEY=${NEON_API_KEY}
      - NEON_PROJECT_ID=${NEON_PROJECT_ID}
      - DRIVER=serverless
    volumes:
      # mount .neon_local state and our repo’s .git so Neon Local can
      # detect/manage branch persistence
      - ./.neon_local/:/scripts/.neon_local
      - ../.git:/scripts/.git:ro,consistent
    networks:
      - app-net
```

I'm receiving the following when running docker compose up: 

```
smartpass-frontend-neon-db-1      | Exception in thread Thread-1 (start_reloader_loop):
smartpass-frontend-neon-db-1      | Traceback (most recent call last):
smartpass-frontend-neon-db-1      |   File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
smartpass-frontend-neon-db-1      |     self.run()
smartpass-frontend-neon-db-1      |   File "/usr/lib/python3.12/threading.py", line 1012, in run
smartpass-frontend-neon-db-1      |     self._target(*self._args, **self._kwargs)
smartpass-frontend-neon-db-1      |   File "/scripts/app/process_manager.py", line 54, in start_reloader_loop
smartpass-frontend-neon-db-1      |     self.start_process()
smartpass-frontend-neon-db-1      |   File "/scripts/app/haproxy_manager.py", line 28, in start_process
smartpass-frontend-neon-db-1      |     self.prepare_config()
smartpass-frontend-neon-db-1      |   File "/scripts/app/haproxy_manager.py", line 14, in prepare_config
smartpass-frontend-neon-db-1      |     if self.manage_branches:
smartpass-frontend-neon-db-1      |        ^^^^^^^^^^^^^^^^^^^^
smartpass-frontend-neon-db-1      | AttributeError: 'HAProxyManager' object has no attribute 'manage_branches'
smartpass-frontend-neon-db-1      | Watching /scripts/.git/HEAD for changes...

Based on "AttributeError: 'HAProxyManager' object has no attribute 'manage_branches'" 
```

However, when using an older image SHA (357e00701ce84ae7d19b394bfb16d8821b4dc109), I'm not receiving the same error and can confirm from the Neon web console that the service is indeed creating a new ephemeral branch. 

I'm assuming using the earlier service config may be useful in reproduction of the crash at `if self.manage_branches:,` due to missing attribute initialization but let me know if I can provide any other details
