### ISSUE TITLE
Automatically detect branch changes

### ISSUE THREAD

**Issue by rena0157** [neondatabase-labs/neon_local#13]
Is there a way to automatically detect when you have changed branches?

I have the following config and am running on Windows:

```yml
services:
  db:
    image: neondatabase/neon_local:latest
    ports:
      - '5432:5432'
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      DRIVER: 'serverless'
    volumes:
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro,consisten
```

**Comment by rena0157** [comment]
Got it to work.. for some reason you have to add the following:

```yml
services:
  db:
    image: neondatabase/neon_local:latest
    ports:
      - '5432:5432'
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      DRIVER: 'serverless'
    volumes:
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/scripts/.git/HEAD:ro,consistent # HAVE TO ADD THIS LINE FOR IT TO TRIGGER CHANGES
      - ./.git/HEAD:/tmp/.git/HEAD:ro,consisten
```
